### ISSUE TITLE
Add a `pattern` option to the `identifier` data type adapter

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#175]
Some identifiers have mandated display formats - e.g.:
 - US SSN: 999-99-999 (https://en.wikipedia.org/wiki/Social_Security_number)
 - US MBI: https://noworldborders.com/2020/01/08/medicare-beneficiary-identifier-required-in-2020/
 - CA SIN: https://en.wikipedia.org/wiki/Social_insurance_number

The `identifier` datatype adapter could take an optional `pattern` argument that can provide a pattern to format the values.
The pattern could match numbers and/or letters to present them in groups with separators. (format TBD).

The pattern could also accept a mapping of system and patterns, so that applications could have a constant somewhere that is passed systematically to the formatter everywhere, and the appropriate pattern is applied based on the identifier system.

A default pattern value could be included that have a number of patterns defined OOB for common systems.

Example usage:

```typescript
const identifier: Identifier = {
  system: "http://hl7.org/fhir/sid/us-ssn",
  value: "75359831"
};

dataTypeAdapter.identifier.format(identifier, { pattern: "999-99-999" }) -> 753-59-831

// Default OOB patterns
dataTypeAdapter.identifier.format(identifier) -> 753-59-831

// Custom app mapping
const IdentifierPatterns: Record<string, string> = {
  "http://hl7.org/fhir/sid/us-ssn": "999-99999",
  "http://my-custom-identifier-system": "999-AA-BBB",
};

dataTypeAdapter.identifier.format(identifier, { pattern: IdentifierPatterns }) -> 753-59831

```

**Comment by jadiaheno** [comment]
# Update on implementation
## 1. String pattern
a. If a pattern string is provided, it's used to format the value
b. If the format fails, the original value is returned. (should we console.warn?)
## 2. Dictionary pattern
a. If the identifier's system is in the system:pattern dictionary, the system is used to format the value
b. If the identifier's system is not in the dictionary, the format fails, the original value is returned (should we console.warn?)
c. If the identifier's system is not in the dictionary, but the system is in the default system's pattern list, the format fails, (should we console.warn that the system is already in the dictionary?)

## 3. Default pattern
a. If the identifier's system is in the default system's pattern list, the default pattern is used to format the value
b. If the identifier's system is not in the default system's pattern list, the format fails, the original value is returned (should we console.warn?)

# Others
## Regex pattern
A regex pattern is the most consistent way to format the value, some identifiers system can have a letter or a number at the same position eg:  the MBI : 3rd and 6th characters 
<img width="903" alt="image" src="https://user-images.githubusercontent.com/13062328/233983044-d51debf1-141e-42e3-b155-7330c1936221.png">

**Comment by julienblin** [comment]
Regex pattern might get too complex though for the majority of cases.
One way is to think about the pattern the same ways as an input mask.

Have a look here: https://github.com/sanniassin/react-input-mask#usage
I really like the possibilities offered by this library: either a simple pattern, or an array of regexes/strings.

**Comment by jadiaheno** [comment]
Thank you for the link. Applying the changes.

What do you think of 2.c? 
> c. If the identifier's system is not in the dictionary, but the system is in the default system's pattern list, the format fails, (should we console.warn that the system is already in the dictionary?)

If the user supplied dictionary does not have the pattern, but it exists in the default pattern. Should we apply the default pattern, or should we do nothing? My POV is doing nothing and returning the initial value. Do you agree?

**Comment by julienblin** [comment]
> If the user supplied dictionary does not have the pattern, but it exists in the default pattern. Should we apply the default pattern, or should we do nothing? My POV is doing nothing and returning the initial value. Do you agree?

Works for me :-)
