### ISSUE TITLE
Investigate R5 support

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#181]
Now that FHIR has officially promoted R5, we should look at how to support it in @bonfhir.

http://hl7.org/fhir/index.html
https://jira.hl7.org/browse/FHIR-5507?filter=19551

**Comment by plauclair** [comment]
Not a fully developed thought, but here I go anyway: we should have a look into exposing types with a /latest instead of a just a specific version as well.

**Comment by julienblin** [comment]
Tackled in V2
