### ISSUE TITLE
`ExpandOperationParameters.filter` should be `string | undefined`

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#37]
See https://github.com/bonfhir/bonfhir/blob/419570de4577fb6425911a5d19f76fde9cc5ebd3/packages/medplum/r4b/medplum-fhir-restful-client-adapter.ts#L262.

We may think about bringing the type in `core` instead of `medplum` as well, since it's a standard operation.

**Comment by opiation** [comment]
Indeed, the `filter` needs to be optional as its [cardinality in the 4b spec suggests][0]. I too would support moving the `ExpandOperationParameters` to `core`.

Should `url` also be optional as its cardinality is also `0..1`?

Lastly, should all the params documented in the spec be a part of the `ExpandOperationParameters` type (regardless of what the implementations do with them)? There are many...

- `valueSet`
- `valueSetVersion`
- `context`
- `contextDirection`
- `filter`
- `date`
- `offset`
- `count`
- `includeDesignations`
- `designation`
- `includeDefinition`
- `activeOnly`
- `excludeNested`
- `excludeNotForUI`
- `excludePostCoordinated`
- `displayLanguage`
- `exclude-system`
- `system-version`
- `check-system-version`
- `force-system-version`
- `return`
> For the `0..*` cardinality, I would recommend `myProp?: Array<...> | null | undefined` as a type signature.

I could see this having a few steps:
- Make `ExpandOperationParameters["filter"]` optional
- Move the `ExpandOperationParameters` type and guard to `core`
- Add remaining params from the spec

Thoughts, @julienblin?

[0]: https://www.hl7.org/fhir/valueset-operation-expand.html
