### ISSUE TITLE
`resourceSearch("List")` is missing the `identifier` method

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#41]
See here: https://hl7.org/fhir/list.html#search

**Comment by ngouy** [comment]
From what I see, none of the rb4 nor the v5 versions (checked into the packages from [here](http://hl7.org/fhir/directory.html)) have the List-Identity search parameter, might be a ... spec bug?

**Comment by ngouy** [comment]
https://jira.hl7.org/browse/FHIR-9353
😿

**Comment by julienblin** [comment]
We can add it to the file for now. I'll see if I find a commit that does that already
