### ISSUE TITLE
Create a `prevUrl` helper / mirror of `nextUrl`

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#50]
See https://github.com/bonfhir/bonfhir/blob/cd9265a98c523681d794307c3a427b478c763e42/packages/core/r4b/fhir-restful-client.ts#L417

**Comment by ngouy** [comment]
Not sure how to do that, given the list don't have this information

![image](https://user-images.githubusercontent.com/12391171/216707131-4793ef2f-543b-4ebf-8607-f452b7ac1742.png)

**Comment by ngouy** [comment]
cc @julienblin

**Comment by julienblin** [comment]
Actually, on the second page there is only a `first` link.
Starting from the 3rd page, should start seeing `previous` link as well.

Something like this:

```typescript
export function prevUrl(bundle: Bundle): string | undefined {
  return (
    bundle.link?.find((link) => link.relation === "previous")?.url ||
    bundle.link?.find((link) => link.relation === "first")?.url
  );
}
```
