### ISSUE TITLE
support for all FHIR primary data types

### ISSUE THREAD

**Issue by ngouy** [bonfhir/bonfhir1_archive#80]
https://www.hl7.org/fhir/datatypes.html#string

- [x] boolean (https://github.com/bonfhir/bonfhir/pull/76)
- [x] decimal (https://github.com/bonfhir/bonfhir/pull/74)
- [x] integer (https://github.com/bonfhir/bonfhir/pull/77)
- [x] URI (https://github.com/bonfhir/bonfhir/pull/83)
- [x] URL (https://github.com/bonfhir/bonfhir/pull/83)
- [x] Canonical (https://github.com/bonfhir/bonfhir/pull/83)
- [x] instant (https://github.com/bonfhir/bonfhir/pull/85)
- [x] date (https://github.com/bonfhir/bonfhir/pull/73)
- [x] datetime (https://github.com/bonfhir/bonfhir/pull/84)
- [x] time (https://github.com/bonfhir/bonfhir/pull/87)
- [x] code https://github.com/bonfhir/bonfhir/pull/88
- [x] markdown https://github.com/bonfhir/bonfhir/pull/97
- [x] unsigned int (alias integer) https://github.com/bonfhir/bonfhir/pull/105
- [x] positive int (alias integer) https://github.com/bonfhir/bonfhir/pull/105
- [x] string (skip) https://github.com/bonfhir/bonfhir/pull/105
- [x] base64binary (skip) https://github.com/bonfhir/bonfhir/pull/105
- [x] oid (skip) https://github.com/bonfhir/bonfhir/pull/105
- [x] id (skip) https://github.com/bonfhir/bonfhir/pull/105
- [x] uuid (skip) https://github.com/bonfhir/bonfhir/pull/105

**Comment by ngouy** [comment]
@julienblin do we want to:
- create a string one
- create aliases (aliases to string for oid/id/uuid and integer for ints)

**Comment by julienblin** [comment]
@ngouy - alright, let's do this to be consistent.

> @julienblin do we want to:
> 
> * create a string one
> * create aliases (aliases to string for oid/id/uuid and integer for ints)

**Comment by ngouy** [comment]
I suggest for now we don't have specific formatted for the string and wait for use cases (for the ellipsis etc ...)

**Comment by julienblin** [comment]
I think the work is done here - closing this.
