### ISSUE TITLE
feat(core): add formatters for General-Purpose Datatypes FHIR

### ISSUE THREAD

**Issue by ngouy** [bonfhir/bonfhir1_archive#94]
- [x] [Attachment](https://hl7.org/fhir/datatypes.html#Attachment) (skip)
- [x] [Range](https://hl7.org/fhir/datatypes.html#Range) https://github.com/bonfhir/bonfhir/pull/97
- [x] [Period](https://hl7.org/fhir/datatypes.html#Period) https://github.com/bonfhir/bonfhir/pull/97
- [x] [Ratio](https://hl7.org/fhir/datatypes.html#Ratio) https://github.com/bonfhir/bonfhir/pull/97
- [x] [RatioRange](https://hl7.org/fhir/datatypes.html#RatioRange) https://github.com/bonfhir/bonfhir/pull/97
- [x] [CodeableConcept](https://hl7.org/fhir/datatypes.html#CodeableConcept) https://github.com/bonfhir/bonfhir/pull/102
- [x] [Coding](https://hl7.org/fhir/datatypes.html#Coding) https://github.com/bonfhir/bonfhir/pull/102
- [x] [SampledData](https://hl7.org/fhir/datatypes.html#SampledData)  (skip)
- [x] [Age](https://hl7.org/fhir/datatypes.html#Age) https://github.com/bonfhir/bonfhir/pull/102
- [x] [Distance](https://hl7.org/fhir/datatypes.html#Distance) https://github.com/bonfhir/bonfhir/pull/102
- [x] [Duration](https://hl7.org/fhir/datatypes.html#Duration) https://github.com/bonfhir/bonfhir/pull/102
- [x] [Count](https://hl7.org/fhir/datatypes.html#Count) https://github.com/bonfhir/bonfhir/pull/102
- [x] [Money](https://hl7.org/fhir/datatypes.html#Money) https://github.com/bonfhir/bonfhir/pull/97
- [x] [MoneyQuantity](https://hl7.org/fhir/datatypes.html#MoneyQuantity) (skip)
- [x] [Annotation](https://hl7.org/fhir/datatypes.html#Annotation) (skip)
- [x] [Timing](https://hl7.org/fhir/datatypes.html#Timing) (skip)
- [x] [Quantity](https://hl7.org/fhir/datatypes.html#Quantity) https://github.com/bonfhir/bonfhir/pull/97
- [x] [SimpleQuantity](https://hl7.org/fhir/datatypes.html#SimpleQuantity) https://github.com/bonfhir/bonfhir/pull/97
- [x] [BackboneType](https://hl7.org/fhir/datatypes.html#BackboneType) (skip)
- [x] [Identifier](https://hl7.org/fhir/datatypes.html#Identifier)
  - [x] array formatter
- [x] [HumanName](https://hl7.org/fhir/datatypes.html#HumanName) https://github.com/bonfhir/bonfhir/pull/105
  - [x] array formatter
- [x] [Address](https://hl7.org/fhir/datatypes.html#Address) https://github.com/bonfhir/bonfhir/pull/105
  - [x] array formatter
- [x] [ContactPoint](https://hl7.org/fhir/datatypes.html#ContactPoint) https://github.com/bonfhir/bonfhir/pull/105
  - [x] array formatter
- [x] [Signature](https://hl7.org/fhir/datatypes.html#Signature) (skip)

**Comment by ngouy** [comment]
@julienblin I'm left with most complicated ones, and even if so far my arbitrary way of formatting objects are doable with common sense, the next ones I will need more guidance. Some I'm just unsure on if how I would do it would be good (annotation, signature, identifier ...) , some I just don't know at all how to deal with them (backbone element, timing, attachment)

**Comment by julienblin** [comment]
Here is what I suggest for e.g. address formatter options:

```typescript
export type FhirAddressFormatOptions = {

  /**
   * The default country to apply if missing from the address.
   */
  defaultCountry?: string | null | undefined;

  /**
   * - standard: display the address without the use, type or period.
   * - full: display the address with the period
   * - extended: display the address with the use, type and period
   */
  style?: "standard" | "full" | "extended" | null | undefined;

  /**
   * True to use text if present, false to never use text - defaults to true
   */
  preferText?: boolean | null | undefined;

  /**
   * The separator to use to join formatted line addresses. Defaults to ", "
   */
  lineSeparator?: string | null | undefined;

  /**
   * When using a list of addresses, either format only the first (after sorting), or all addresses in a list
   */
  select: "first" | "all";

  /**
   * When using a list of addresses, the sort order for the `use` attribute.
   * Defaults to home, work, billing, temp, old, undefined
   * 
   * To filter out specific values, do not include them in the sortOrder.
   */
  sortOrder?: Array<Address["use"] | undefined> | null | undefined;

  useValueSetExpansions?: FhirCodeFormatOptions["valueSetExpansions"];
  typeValueSetExpansions?: FhirCodeFormatOptions["valueSetExpansions"];
};

export interface FhirAddressTypeAdapter {
  locale: FhirDataTypeAdapter["locale"];

  /**
   * Format a FHIR address
   *
   * @see https://hl7.org/fhir/datatypes.html#address
   */
  format(
    value: Address[] | Address | null | undefined,
    options?: FhirAddressFormatOptions | null | undefined
  ): string;
}
```
