### ISSUE TITLE
Audit usage of lodash and internalize and/or optimize imports per file.

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir1_archive#96]
See https://www.blazemeter.com/blog/import-lodash-libraries for reference

**Comment by ngouy** [comment]
I'm wondering what is the play here
Not long ago I used `import { something } from "lodash"` but for a reason I don't remember we changed it to `import _ from "lodash"`

**Comment by julienblin** [comment]
> I'm wondering what is the play here
> Not long ago I used `import { something } from "lodash"` but for a reason I don't remember we changed it to `import _ from "lodash"`

See #110.

> This is the only method that works either on ESM and CJS, and authorize lodash tree shaking.
We previously changed the import to stay compatible with ESM bundling. This is the way 🤞 that we don;t have to change it again.
